name: ♻️ 🚚 Add or change your product name keyref
description: The official short name and full name of your product in cloudoekeyrefs.yml.
title: "New or changed keyref for <product>"
labels: [Build Request, keyref, terminology]
assignees:
  - cjcarpen
  - allen-dean
  - Kent-Hall
  - mtompki
projects:
  - SirSpidey/1
body:
  - type: markdown
    attributes:
      value: |
        For more information about key references (keyrefs) in IBM Cloud, see [Using keyrefs for product names](https://test.cloud.ibm.com/docs-internal/writing?topic=writing-keyrefs) in the writers guide.

# Needed by
  - type: markdown
    attributes:
      value: Provide the date when you want the change to go live. You must get approvals here before the change will be made.

# Changed keyref
  - type: markdown
    attributes:
      value: "## For keyrefs that are changing"
  - type: markdown
    attributes:
      value: |
          Assess how the keyref change affects other doc subcollections. Search the `cloud-docs` and `cloud-docs-solutions` orgs for the keyrefs that you are changing. Uses of your keyref are displayed on the Code tab.

          For example:

          - https://github.ibm.com/search?q=org%3Acloud-docs+openshiftshort&type=code
          - https://github.ibm.com/search?q=org%3Acloud-docs-solutions+openshiftshort&type=code

          If it's a commonly used keyref or this is a significant change, contact teams directly. The IBM Cloud docs team can help you identify the teams.
  - type: checkboxes
    id: searched-uses
    attributes:
      label: Searched
      options:
        - label: I searched for my keyrefs across Cloud docs
          required: true
  - type: markdown
    attributes:
      value: At least a week before the change goes live, post about the change in the `#docs` channel so that teams know the target date of the change and have time to update their docs.
  - type: checkboxes
    id: announce-change-pre
    attributes:
      label: Post about the change before it goes live
      options:
        - label: I posted about the change ahead of time
          required: true
  - type: input
    id: announce-change-pre-url
    attributes:
      label: Link to your Slack post
      description: |
        1.  From the Slack desktop app, hover over the message.
        1.  Click the 3-dot **More Actions** icon.
        1.  Click **Copy link**.
      placeholder: https://ibm-cloudplatform.slack.com/archives/C03UVUZFK/p1711147227154869

# Approver information
  - type: markdown
    attributes:
      value: "## Approver information"
  - type: markdown
    attributes:
      value: |

        Provide a list of approvers. Mention them by typing `@` plus their GitHub Enterprise username. Include at least 1 technical lead and 1 business lead.
  - type: input
    id: tech-approver
    attributes:
      label: Technical lead
      placeholder: <@ID> please approve this name change in IBM Cloud docs.
    validations:
      required: true
  - type: input
    id: biz-approver
    attributes:
      label: Business lead
      description: Usually your product manager
      placeholder: <@ID> please approve this name change in IBM Cloud docs.
    validations:
      required: true
  - type: textarea
    id: other-approvers
    attributes:
      label: Other approvers
      description: Include others who need to approve this change.
      placeholder:  <@ID>
    validations:
      required: false

# Post-change details
  - type: markdown
    attributes:
      value: "## After the change goes live"
  - type: textarea
    id: announce-change-post
    attributes:
      label: Post again after the change goes live
      description: After the change is live, post details again in the `#docs` channel to let teams know that the change was made.
      value: "- [ ] I posted information in the `#docs` channel that the keyref is changed."
    validations:
      required: false

# Stuff for build admins
  - type: markdown
    attributes:
      value: "## For build admins"
  - type: textarea
    id: admin-instructions
    attributes:
      label: Information for build admins
      value: For build admins. After all the listed reviewers approve, follow steps in [Keyrefs](https://github.ibm.com/cloud-doc-build/docs-build/wiki/Keyrefs).
