name: ✨ 👷 Onboarding request to join IBM Cloud content development
description: I am new to IBM Cloud docs. Please help me onboard.
title: "Onboarding request for <name>"
labels: [Build Request, onboarding]
assignees:
  - cjcarpen
  - SirSpidey
  - Kent-Hall
  - mtompki
projects:
  - SirSpidey/1
body:
  - type: markdown
    attributes:
      value: >
        Use this template to provide us with the information to get you access.
        For more information about getting access and the tools, see [Getting started](https://test.cloud.ibm.com/docs-internal/writing?topic=writing-get-started-onboarding) in the writers guide.

# Contact info
  - type: markdown
    attributes:
      value: "## Provide Your IDs"
  - type: markdown
    attributes:
      value: Provide the email address, GitHub, GitHub Enterprise, and Slack information for the person we're onboarding.
  - type: input
    id: email
    attributes:
      label: IBM Email Address
    validations:
      required: true
  - type: input
    id: ghe-id
    attributes:
      label: GitHub Enterprise ID
      description: Enter the person's GHE ID. [In GHE](https://github.ibm.com/), click your profile icon in the upper-right of the screen and look for "Signed in as" for your ID.
      placeholder: "example: https://github.ibm.com/allen-dean"
    validations:
      required: true
  - type: input
    id: gh-id
    attributes:
      label: Public GitHub ID
      description: Enter the person's public GitHub ID. [In GH](https://github.com/), click your profile icon in the upper-right of the screen. Your ID is above your name. Your public GH ID might not be the same as your GitHub Enterprise ID.
      placeholder: "example: https://github.com/sirspidey"
    validations:
      required: true
  - type: input
    id: slack-id
    attributes:
      label: Slack Name
      description: |
        Enter the person's Slack display name.

        1.  From the Slack desktop app, click your profile picture in the sidebar.
        1.  Select **Profile**.
        1.  Click the 3-dot **More Actions** icon.
        1.  Click **Copy display name**.
      placeholder: "example: @allen.dean"
    validations:
      required: true

# Request for update to title
  - type: markdown
    attributes:
      value: "## Update the Issue Title"
  - type: checkboxes
    id: update-title
    attributes:
      label: Update the Issue Title
      description: Replace `<name>` in **Add a title** at the top of this form.
      options:
        - label: I updated the person's name in the issue title
          required: true

# Additional info
  - type: markdown
    attributes:
      value: "## Additional information"
  - type: textarea
    id: other-info
    attributes:
      label: Anything else?
      description: If you have more information you think we need, you can add it here.
    validations:
      required: false

# Stuff for build admins
  - type: textarea
    id: admin-instructions
    attributes:
      label: For build admins only
      value: For build admins. Follow steps in [Onboarding new writers to IBM Cloud docs](https://github.ibm.com/cloud-doc-build/docs-build/wiki/Onboarding-new-writers-to-IBM-Cloud-docs) tasks.
