name: 🆕 Build request - New docs subcollection
description: I want to deliver a new set of public or internal content in the IBM Cloud docs
title: "Build request: New subcollection for <my service>"
labels: [Build Request]
assignees:
  - cjcarpen
  - SirSpidey
body:
  - type: markdown
    attributes:
      value: "### Type of docs"
  - type: markdown
    attributes:
      value: |
        Use this template to request a repo for new public or internal content in IBM Cloud docs.

        Make sure you update `<my service>` in **Add a title**.

  - type: dropdown
    attributes:
      label: "The type of docs you will publish"
      description: |
        Are you delivering public product docs for services or software, or internal-only content?

        - If your service docs will be publicly available at some point, choose one of the **External** options.
            - Service docs example: [Virtual server for VPC](https://cloud.ibm.com/docs/vpc)
            - Software product docs example: [Power Virtual Server for SAP HANA](https://cloud.ibm.com/docs/sap-powervs).
        - If your content will never be available to non-IBMers, chose **Internal-only**.
            - Example internal-only docs: [Supplier Management Framework](https://test.cloud.ibm.com/docs-internal/supplier-mgmt-framework).
            - Internal-only guides are for internal guidance, such as a developer guide. Example: [Developing in IBM Cloud](https://test.cloud.ibm.com/docs-internal/get-coding).
      options:
        - Docs for an IBM Cloud service (External)
        - Docs for an IBM Cloud software product (External)
        - Internal-only docs
        - Guides (Internal-only)
      default: 1
    validations:
      required: true

  - type: textarea
    id: docs-description
    attributes:
      label: What will this doc set cover?
      description: Provide a brief description of what content will be in this repo. This information helps confirm the type of docs.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Docs for a product on IBM Cloud"
  - type: markdown
    attributes:
      value: If you selected external docs for an IBM Cloud service or software product, include information from your product's entry. Skip this section if your docs aren't associated with a product.
  - type: input
    id: gc-url
    attributes:
      label: Global Catalog URL
      description: To find your Global Catalog record, search https://globalcatalog.test.cloud.ibm.com/search.
    validations:
      required: false
  - type: input
    id: gc-service-name
    attributes:
      label: Global Catalog service name
      description: From the Global Catalog entry for your product, enter the value in the `Name` column. For example, the service name for Hyper Protect Crypto Services is `hs-crypto`. We use the service name as your docs repository name, and it will be part of your docs URL.
    validations:
      required: false
  - type: textarea
    id: sf-details
    attributes:
      label: Links to your Service Framework issues
      description: |
        Both services and software must follow the Service Framework requirements, which for documentation include the [User Experience (UX)](https://test.cloud.ibm.com/docs/service-framework?topic=service-framework-user-experience-ux-) requirements **UX025 Documentation** and **UX033 End-to-end Content Experience Review**. You should have an issue for each Service Framework requirement.
      placeholder: |
        Link to your UX025 issue:
        Link to your UX033 issue:
  - type: markdown
    attributes:
      value: "### No product on IBM Cloud"
  - type: markdown
    attributes:
      value: However, if your docs are not associated with a product on IBM Cloud and you selected Internal-only docs, what name would you like for the new docs repo?
  - type: input
    id: repo-name
    attributes:
      label: Suggested repo name
      description: |
        Add a value here only if you can't specify your Global Catalog information previously.

        This value is used as your docs repository name and will be part of your docs URL.
        - All lowercase and fewer than 32 characters
        - No spaces, but hyphens (`-`) are allowed
      placeholder: "example: terraform-handbook"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "### Your GitHub and Slack IDs"
  - type: markdown
    attributes:
      value: Provide the GitHub, GitHub Enterprise, and Slack information for the person who will be the main docs contact. We use this information to provide access to your repo and build channels.
  - type: markdown
    attributes:
      value: ℹ️ **Tip** You can add more contributors after your repo is created.
  - type: input
    id: ghe-id
    attributes:
      label: GitHub Enterprise ID
      description: Enter your GHE ID. Click your profile icon in the upper-right of the screen and look for "Signed in as". That is your ID.
      placeholder: "example: https://github.ibm.com/cjcarpen"
    validations:
      required: true
  - type: input
    id: gh-id
    attributes:
      label: Public GitHub ID
      description: Enter your public GitHub ID. Click your profile icon in the upper-right of the screen. Your ID is above your name.
      placeholder: "example: https://github.com/cjcarpen"
    validations:
      required: true
  - type: input
    id: slack-id
    attributes:
      label: Slack Name
      description: |
        Enter your slack display name.

        1.  From your Slack desktop app, click your profile picture in the sidebar.
        1.  Select **Profile**.
        1.  Click the 3-dot **More Actions** icon.
        1.  Click **Copy display name**.
      placeholder: "example: @carolyn"
    validations:
      required: true
