name: 🆕 Build request - New docs subcollection
description: I want to deliver a new set of public or internal content in the IBM Cloud docs
title: "Build request: New subcollection for <my service>"
labels: [Build Request]
assignees:
  - cjcarpen
  - SirSpidey
body:
  - type: markdown
    attributes:
      value: "### Type of docs"
  - type: markdown
    attributes:
      value: |
        Use this template to request a repo for new public or internal content in IBM Cloud docs.

        Make sure you update `<my service>` in **Add a title**.

  - type: dropdown
    attributes:
      label: "The type of docs you will publish"
      description: |
        Are you delivering public product docs for services or software, or internal-only content?

        - If your service docs ever will be publicly available, choose external.

            - Example service docs: [Virtual server for VPC](https://cloud.ibm.com/docs/vpc)
            - Example software docs: [Power Virtual Server for SAP HANA](https://cloud.ibm.com/docs/sap-powervs).
        - Internal-only docs are added to a separate org, and your content will never be available to non-IBMers. Example: [Supplier Management Framework](https://test.cloud.ibm.com/docs-internal/supplier-mgmt-framework).
            - Guidance docs are collections such as developer guides. Example: [Developing in IBM Cloud](https://test.cloud.ibm.com/docs-internal/get-coding).
      options:
        - External docs for an IBM Cloud service (default)
        - External docs for an IBM Cloud software product
        - Internal-only docs
        - Internal-only guides
      default: 0
    validations:
      required: true

  - type: textarea
    id: docs-description
    attributes:
      label: What will this doc set cover?
      description: Provide a brief description of what content will be in this repo. This information helps confirm the type of docs.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Docs for a product on IBM Cloud"
  - type: markdown
    attributes:
      value: If your docs are associated with a product on IBM Cloud, include information from your product's entry. Skip this section if your docs aren't associated with a product.
  - type: input
    id: gc-url
    attributes:
      label: Global Catalog URL
      description: To find your Global Catalog record, search https://globalcatalog.test.cloud.ibm.com/search.
    validations:
      required: false
  - type: input
    id: gc-service-name
    attributes:
      label: Global Catalog service name
      description: From the Global Catalog entry for your product, enter the value in the `Name` column. For example, the service name for Hyper Protect Crypto Services is `hs-crypto`.
    validations:
      required: false
  - type: textarea
    id: sf-details
    attributes:
      label: Links to your Service Framework issues
      description: |
        Both services and software must follow the Service Framework requirements, which for documentation include the [User Experience (UX)](https://test.cloud.ibm.com/docs/service-framework?topic=service-framework-user-experience-ux-) requirements **UX025 Documentation** and **UX033 End-to-end Content Experience Review**.

        You should have an issue for each Service Framework requirement.
      placeholder: |
        Link to your UX025 issue:
        Link to your UX033 issue:
  - type: markdown
    attributes:
      value: "### No product on IBM Cloud"
  - type: markdown
    attributes:
      value: However, if your docs are not associated with a product on IBM Cloud, what name would you like for the new docs repo?
  - type: input
    id: repo-name
    attributes:
      label: Suggested repo name
      description: |

        This value is used as your docs repository name and will be part of your docs URL.
        - All lowercase
        - Can't include spaces but can include hyphens (`-`)
        - Fewer than 32 characters
      placeholder: "example: terraform-handbook"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "### Your GitHub and Slack IDs"
  - type: markdown
    attributes:
      value: Provide your GitHub, GitHub Enterprise, and Slack information. We use this information to provide you access to your repo and build channels.
  - type: input
    id: ghe-id
    attributes:
      label: GitHub Enterprise ID
      description: Enter your GHE ID. Click your profile icon in the upper-right of the screen and look for "Signed in as". That is your ID.
      placeholder: "example: https://github.ibm.com/cjcarpen"
    validations:
      required: true
  - type: input
    id: gh-id
    attributes:
      label: Public GitHub ID
      description: Enter your public GitHub ID. Click your profile icon in the upper-right of the screen. Your ID is above your name.
      placeholder: "example: https://github.com/cjcarpen"
    validations:
      required: true
  - type: input
    id: slack-id
    attributes:
      label: Slack Name
      description: |
        Enter your slack display name.

        1.  From your Slack desktop app, click your profile picture in the sidebar.
        1.  Select **Profile**.
        1.  Click the 3-dot **More Actions** icon.
        1.  Click **Copy display name**.
      placeholder: "example: @carolyn"
    validations:
      required: true
