name: Improve the docs
description: Suggest an improvement to the content in an existing docs topic.
body:

# Contributing info
  - type: markdown
    attributes:
      value: "## About contributing to the docs"
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute to the IBM Cloud docs.

        :information_source: **Tip:** IBMers, don't use this repo to report issues. View the topic in the internal IBM Cloud docs staging site and open a doc issue from there.

        If your comments are about an IBM Cloud product, create an issue instead at IBM Cloud Support. Here's how:
            - If you're logged in to IBM Cloud, go directly to the [Support center](https://cloud.ibm.com/unifiedsupport/supportcenter) to review your product topics and featured FAQs, open or manage a support case, or search community content.
            - If you can't log in to your account, start a chat by going to the [IBM Cloud Support](https://www.ibm.com/cloud/support) page and clicking **Let's talk**.

# The issue details
  - type: textarea
    attributes:
      label: Which topic are you reporting about?
      description: Include a link to the docs topic in IBM Cloud.
      placeholder: https://cloud.ibm.com/docs/ ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: What do you think needs to be updated?
      description: |
        - Is something wrong or unclear? Provide information about what you see versus what you expect to see.
        - Is something missing? Provide as much detail as you can to help us understand the change that you want to see.
    validations:
      required: true

# Additional info
  - type: markdown
    attributes:
      value: "## Additional information"
  - type: textarea
    id: other-info
    attributes:
      label: Anything else?
      description: If you have more information or screenshots that you think we need, add them here.
    validations:
      required: false
